### ISSUE TITLE
error when use 'nbdt-hierarchy'

### ISSUE THREAD

**Issue by zhuyi3625** [alvinwan/neural-backed-decision-trees#14]
when run command 'nbdt-hierarchy' in ubuntu 18.04
**nbdt-hierarchy --checkpoint=wrn28_10_cifar10 --dataset=CIFAR10
nbdt-hierarchy --vis-sublabels --vis-zoom=1.25 --dataset=CIFAR10 --arch=wrn28_10_cifar10**
Here is ModuleNotFoundError: No module named 'nbdt.thirdparty',
I wonder what happened

**Comment by alvinwan** [comment]
Is your system default python3? I just tried `pip install nbdt` (installing `nbdt-0.0.4`) and `nbdt-hierarchy --help` works for me on Ubuntu 18.04. However, I ran this from within a conda environment with a python3 default.

**Comment by zhuyi3625** [comment]
Traceback (most recent call last):
  File "/data/anaconda3/bin/nbdt-hierarchy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/M808/zhuyi/NBDTNemaTest/nbdt/bin/nbdt-hierarchy", line 5, in <module>
    from nbdt.thirdparty.wn import maybe_install_wordnet
ModuleNotFoundError: No module named 'nbdt.thirdparty'

It's the full error tips

**Comment by zhuyi3625** [comment]
> Is your system default python3? I just tried `pip install nbdt` (installing `nbdt-0.0.4`) and `nbdt-hierarchy --help` works for me on Ubuntu 18.04. However, I ran this from within a conda environment with a python3 default.

Traceback (most recent call last):
File "/data/anaconda3/bin/nbdt-hierarchy", line 7, in
exec(compile(f.read(), file, 'exec'))
File "/data/M808/zhuyi/NBDTNemaTest/nbdt/bin/nbdt-hierarchy", line 5, in
from nbdt.thirdparty.wn import maybe_install_wordnet
ModuleNotFoundError: No module named 'nbdt.thirdparty'

It's the full error tips

**Comment by alvinwan** [comment]
Thanks for your traceback, but same question -- is your environment using python2 or python3? I was able to setup the repository inside a conda environment with python3 successfully, using the below:

```
conda create -n nbdt python=3.7
git clone git@github.com:alvinwan/neural-backed-decision-trees.git  # or use https to clone
cd neural-backed-decision-trees
python setup.py develop
nbdt-hierarchy --help
```

**Comment by zhuyi3625** [comment]
> Thanks for your traceback, but same question -- is your environment using python2 or python3? I was able to setup the repository inside a conda environment with python3 successfully, using the below:
> 
> ```
> conda create -n nbdt python=3.7
> git clone git@github.com:alvinwan/neural-backed-decision-trees.git  # or use https to clone
> cd neural-backed-decision-trees
> python setup.py develop
> nbdt-hierarchy --help
> ```

there still an unexpected question,
using command **nbdt-wnids --dataset=CIFAR10**,
error tips,
Traceback (most recent call last):
  File "/data/anaconda3/envs/nbdt/bin/nbdt-wnids", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/data/M808/zhuyi/NBDTNemaTest/nbdt/bin/nbdt-wnids", line 49, in <module>
    print('keys',data.custom.keys)
AttributeError: module 'nbdt.data.custom' has no attribute 'keys'

there is no **attribute 'keys'** in **custom.py**
